<?php

if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_form-3',
        'title' => 'form',
        'fields' => array (

            array (
                'key' => 'field_5616b5766cji7',
                'label' => __('Form Name', 'formularia'),
                'name' => 'form_name',
                'type' => 'text',
                'default_value' => '',
                'layout' => 'vertical',
            ),

            array (
                'key' => 'field_5616b8c83aa94',
                'label' => __('IDENTITY', 'formularia'),
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5616b5766c0b8',
                'label' => __('Firstname', 'formularia'),
                'name' => 'first_name',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b5766ckd9',
                'label' => __('Name', 'formularia'),
                'name' => 'name',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b68e471b1',
                'label' => __('Civility', 'formularia'),
                'name' => 'civility',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b68e471b0',
                'label' => __('Birthday', 'formularia'),
                'name' => 'birthday',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bc0fe310e',
                'label' => __('City of birth', 'formularia'),
                'name' => 'city_of_birth',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bc0fe310g',
                'label' => __('Department of birth (French)', 'formularia'),
                'name' => 'department_of_birth',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bc0fe310h',
                'label' => __('Country of birth', 'formularia'),
                'name' => 'country_of_birth',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bc0fe310f',
                'label' => __('Nationality', 'formularia'),
                'name' => 'nationality',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bc0fe310d',
                'label' => __('Age', 'formularia'),
                'name' => 'age',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bfca327fb',
                'label' => __('Name of birth', 'formularia'),
                'name' => 'name_of_birth',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c070327fd',
                'label' => __('Maiden name', 'formularia'),
                'name' => 'maiden_name',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616ba470a400',
                'label' => __('CONTACT', 'formularia'),
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5616b667471a2',
                'label' => __('Mail', 'formularia'),
                'name' => 'mail',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b667471a9',
                'label' => __('Confirmation Mail', 'formularia'),
                'name' => 'confirmation_mail',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5616b667471a2',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),

                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b68f471b3',
                'label' => __('Subject of the mail', 'formularia'),
                'name' => 'subject_mail',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b68f471b2',
                'label' => __('Text', 'formularia'),
                'name' => 'text',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bde134418',
                'label' => __('Message', 'formularia'),
                'name' => 'message',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bdee34419',
                'label' => __('Comment', 'formularia'),
                'name' => 'comment',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b68d471a6',
                'label' => __('Mobile phone number', 'formularia'),
                'name' => 'mobile_phone_number',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bc4be310f',
                'label' => __('House phone number', 'formularia'),
                'name' => 'house_phone_number',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bc6ae3110',
                'label' => __('Office phone number', 'formularia'),
                'name' => 'office_phone_number',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bc21e310e',
                'label' => __('Fax', 'formularia'),
                'name' => 'fax',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b9e7198ce',
                'label' => __('ADRESS', 'formularia'),
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5616b68e471af',
                'label' => __('Adress', 'formularia'),
                'name' => 'adress',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b68e471ae',
                'label' => __('Zip code', 'formularia'),
                'name' => 'zip_code',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b68e471ad',
                'label' => __('City', 'formularia'),
                'name' => 'city',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b68e471ac',
                'label' => __('Country', 'formularia'),
                'name' => 'country',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616be0acfa73',
                'label' => __('Name of the street', 'formularia'),
                'name' => 'name_street',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616be09cfa72',
                'label' => __('Number of the street', 'formularia'),
                'name' => 'number_street',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c55bc2939',
                'label' => __('Longitude', 'formularia'),
                'name' => 'longitude',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c568c293a',
                'label' => __('Latitude', 'formularia'),
                'name' => 'latitude',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616be08cfa71',
                'label' => __('Cedex', 'formularia'),
                'name' => 'cedex',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616be08cfa70',
                'label' => __('Bis / Ter / Quater', 'formularia'),
                'name' => 'btq',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616be05cfa6f',
                'label' => __('Type of street', 'formularia'),
                'name' => 'type_street',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bf6b6e36d',
                'label' => __('Province', 'formularia'),
                'name' => 'province',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bf766e36e',
                'label' => __('Department', 'formularia'),
                'name' => 'department',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bf816e36f',
                'label' => __('Region', 'formularia'),
                'name' => 'region',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616ba67cedd5',
                'label' => __('CONNEXION / INSCRIPTION', 'formularia'),
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5616b68d471ab',
                'label' => __('Host identifier', 'formularia'),
                'name' => 'host_identifier',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b68d471aa',
                'label' => __('Pseudo', 'formularia'),
                'name' => 'pseudo',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b68d471ge',
                'label' => __('Password', 'formularia'),
                'name' => 'password',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b68d471a9',
                'label' => __('Confirmation of password', 'formularia'),
                'name' => 'confirmation_password',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_5616b68d471ge',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_56195aa978672',
                'label' => __('Secret Question', 'formularia'),
                'name' => 'secret_question',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_56195ad87acc4',
                'label' => __('Secret question 1', 'formularia'),
                'name' => 'secret_question_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56195aa978672',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195af886b4a',
                'label' => __('Secret question 2', 'formularia'),
                'name' => 'secret_question_2',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56195aa978672',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b05d7e3a',
                'label' => __('Secret question 3', 'formularia'),
                'name' => 'secret_question_3',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56195aa978672',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b1cd7e3b',
                'label' => __('Secret question 4', 'formularia'),
                'name' => 'secret_question_4',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56195aa978672',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b2bd7e3c',
                'label' => __('Secret question 5', 'formularia'),
                'name' => 'secret_question_5',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56195aa978672',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b34d7e3d',
                'label' => __('Secret question 6', 'formularia'),
                'name' => 'secret_question_6',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56195aa978672',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b48d7e3e',
                'label' => __('Secret question 7', 'formularia'),
                'name' => 'secret_question_7',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56195aa978672',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b53d7e3f',
                'label' => __('Secret question 8', 'formularia'),
                'name' => 'secret_question_8',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56195aa978672',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b5ed7e40',
                'label' => __('Secret question 9', 'formularia'),
                'name' => 'secret_question_9',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56195aa978672',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b67d7e41',
                'label' => __('Secret question 10', 'formularia'),
                'name' => 'secret_question_10',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56195aa978672',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5616b68d471a7',
                'label' => __('Answer secret question', 'formularia'),
                'name' => 'answer_secret_question',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_56195aa978672',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b9653aa95',
                'label' => __('BANK CARD', 'formularia'),
                'name' => '',
                'type' => 'tab',
            ),

            array (
                'key' => 'field_561a7d7cd3b4c',
                'label' => __('Type of Bank Card', 'formularia'),
                'name' => 'type_bank_card',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_56195ad87acc5',
                'label' => __('Type of Bank Card 1', 'formularia'),
                'name' => 'type_bank_card_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561a7d7cd3b4c',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => 'Visa',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195af886b4b',
                'label' => __('Type of Bank Card 2', 'formularia'),
                'name' => 'type_bank_card_2',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561a7d7cd3b4c',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => 'Mastercard',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b05d7e3b',
                'label' => __('Type of Bank Card 3', 'formularia'),
                'name' => 'type_bank_card_3',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561a7d7cd3b4c',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => 'American Express',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b1cd7e3c',
                'label' => __('Type of Bank Card 4', 'formularia'),
                'name' => 'type_bank_card_4',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561a7d7cd3b4c',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => 'Maestro',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b2bd7e3d',
                'label' => __('Type of Bank Card 5', 'formularia'),
                'name' => 'type_bank_card_5',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561a7d7cd3b4c',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => 'Blue Card',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b34d7e3e',
                'label' => __('Type of Bank Card 6', 'formularia'),
                'name' => 'type_bank_card_6',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561a7d7cd3b4c',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b48d7e3f',
                'label' => __('Type of Bank Card 7', 'formularia'),
                'name' => 'type_bank_card_7',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561a7d7cd3b4c',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b53d7e3h',
                'label' => __('Type of Bank Card 8', 'formularia'),
                'name' => 'type_bank_card_8',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561a7d7cd3b4c',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b5ed7e42',
                'label' => __('Type of Bank Card 9', 'formularia'),
                'name' => 'type_bank_card_9',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561a7d7cd3b4c',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_56195b67d7e45',
                'label' => __('Type of Bank Card 10', 'formularia'),
                'name' => 'type_bank_card_10',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561a7d7cd3b4c',
                            'operator' => '==',
                            'value' => 'oui',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),

            array (
                'key' => 'field_5616b68b471a4',
                'label' => __('Number of Bank Card', 'formularia'),
                'name' => 'number_bank_card',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b68b471a8',
                'label' => __('Date expiration Bank Card', 'formularia'),
                'name' => 'date_expiration_bank_card',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b7de92703',
                'label' => __('Security password of Bank Card', 'formularia'),
                'name' => 'security_password_bank_card',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616b7dd92702',
                'label' => __('Name user of Bank Card', 'formularia'),
                'name' => 'name_user_bank_card',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bc88472f9',
                'label' => __('OTHERS', 'formularia'),
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5616b7db92701',
                'label' => __('Occupation', 'formularia'),
                'name' => 'occupation',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616bc90472fa',
                'label' => __('Social Insurance number', 'formularia'),
                'name' => 'social_insurance_number',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c0c7327ff',
                'label' => __('WEBSITE', 'formularia'),
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5616c0ba327fe',
                'label' => __('Website', 'formularia'),
                'name' => 'website',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c0d432800',
                'label' => __('Facebook Account', 'formularia'),
                'name' => 'facebook_account',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c0f732801',
                'label' => __('Twitter Account', 'formularia'),
                'name' => 'twitter_account',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c10332802',
                'label' => __('LinkedIn Account', 'formularia'),
                'name' => 'linkedin_account',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c10f32803',
                'label' => __('Pinterest Account', 'formularia'),
                'name' => 'pinterest_account',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c11932804',
                'label' => __('Google + Account', 'formularia'),
                'name' => 'gogle_plus_account',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c12432805',
                'label' => __('Instagram Account', 'formularia'),
                'name' => 'instagram_account',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c14632806',
                'label' => __('Viadeo Account', 'formularia'),
                'name' => 'viadeo_account',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c38e30f40',
                'label' => __('E-COMMERCE', 'formularia'),
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5616c3a630f42',
                'label' => __('File number', 'formularia'),
                'name' => 'file_number',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c3cb30f43',
                'label' => __('Order number', 'formularia'),
                'name' => 'order_number',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c4a630f48',
                'label' => __('COMPANY', 'formularia'),
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5616c3d630f44',
                'label' => __('Company', 'formularia'),
                'name' => 'company',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c42d30f45',
                'label' => __('Name of the company', 'formularia'),
                'name' => 'name_company',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c43930f46',
                'label' => __('SIRET number', 'formularia'),
                'name' => 'siret_number',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c48630f47',
                'label' => __('IBAN number', 'formularia'),
                'name' => 'iban_number',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c5eb3b717',
                'label' => __('DATES', 'formularia'),
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_5616c5f73b718',
                'label' => __('Date', 'formularia'),
                'name' => 'date',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c6053b719',
                'label' => __('Date of beginning', 'formularia'),
                'name' => 'beginning_date',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_5616c60f3b71a',
                'label' => __('Date of end', 'formularia'),
                'name' => 'end_date',
                'type' => 'checkbox',
                'choices' => array (
                    'oui' => 'oui',
                ),
                'default_value' => '',
                'layout' => 'vertical',
            ),

            array (
                'key' => 'field_5616c5eb3b718',
                'label' => __('ADD A FIELD', 'formularia'),
                'name' => '',
                'type' => 'tab',
            ),
            array (
                'key' => 'field_561aaf2ab6b78',
                'label' => __('Type of field', 'formularia'),
                'name' => 'type of field',
                'type' => 'radio',
                'choices' => array (
                    'aucun' => __('None'),
                    'new_text' => __('Text short'),

                    'new_textarea' => __('Text long'),
                    'new_select_option' => __('Select Options'),
                    'new_radio' => __('Radio 1 choise'),
                    'new_checkbox' => __('Checkbox'),
                    'new_color_selector' => __('Color Selector'),
                    'new_numerique' => __('Numbers'),
                    'new_button' => __('Button'),
                    'new_file' => __('File'),
                    'new_password' => __('Password'),
                    'new_date' => __('Date (dd/mm/yyyy)'),

                ),
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
            ),
            array (
                'key' => 'field_561ab1c6fd24d',
                'label' => __('Label new Text', 'formularia'),
                'name' => 'label_new_text_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_text',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab271dce67',
                'label' => __('Label new Textarea', 'formularia'),
                'name' => 'label_new_textarea_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_textarea',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab2c022678',
                'label' => __('Label new Select Option', 'formularia'),
                'name' => 'label_new_select_option_1_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_select_option',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab2ea2054b',
                'label' => __('Label Field 1 Select Option', 'formularia'),
                'name' => 'label_new_select_option_1_1_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_select_option',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab3252a757',
                'label' => __('Label Field 2 Select Option ', 'formularia'),
                'name' => 'label_new_select_option_1_1_2',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_select_option',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab336ba1f7',
                'label' => __('Label Field 3 Select Option', 'formularia'),
                'name' => 'label_new_select_option_1_1_3',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_select_option',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab341ba490',
                'label' => __('Label Field 4 Select Option', 'formularia'),
                'name' => 'label_new_select_option_1_1_4',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_select_option',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab34ee4d20',
                'label' => __('Label Field 5 Select Option', 'formularia'),
                'name' => 'label_new_select_option_1_1_5',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_select_option',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab38b2d049',
                'label' => __('Label Field 6 Select Option', 'formularia'),
                'name' => 'label_new_select_option_1_1_6',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_select_option',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab3992d04a',
                'label' => __('Label Field 7 Select Option', 'formularia'),
                'name' => 'label_new_select_option_1_1_7',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_select_option',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab3a6209eb',
                'label' => __('Label Field 8 Select Option', 'formularia'),
                'name' => 'label_new_select_option_1_1_8',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_select_option',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab3b4209ec',
                'label' => __('Label Field 9 Select Option', 'formularia'),
                'name' => 'label_new_select_option_1_1_9',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_select_option',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab3c1209ed',
                'label' => __('Label Field 10 Select Option ', 'formularia'),
                'name' => 'label_new_select_option_1_1_10',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_select_option',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab3e3f4521',
                'label' => __('Label new Radio', 'formularia'),
                'name' => 'label_new_radio_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_radio',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab41183e40',
                'label' => __('Label Field 1 radio', 'formularia'),
                'name' => 'label_new_radio_1_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_radio',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab434f0d5c',
                'label' => __('Label Field 2 radio', 'formularia'),
                'name' => 'label_new_radio_1_2',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_radio',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab440f0d5d',
                'label' => __('Label Field 3 radio', 'formularia'),
                'name' => 'label_new_radio_1_3',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_radio',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab44df0d5e',
                'label' => __('Label Field 4 radio', 'formularia'),
                'name' => 'label_new_radio_1_4',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_radio',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab458f0d5f',
                'label' => __('Label Field 5 radio', 'formularia'),
                'name' => 'label_new_radio_1_5',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_radio',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab460f0d60',
                'label' => __('Label Field 6 radio', 'formularia'),
                'name' => 'label_new_radio_1_6',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_radio',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab468f0d61',
                'label' => __('Label Field 7 radio', 'formularia'),
                'name' => 'label_new_radio_1_7',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_radio',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab471f0d62',
                'label' => __('Label Field 8 radio ', 'formularia'),
                'name' => 'label_new_radio_1_8',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_radio',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab47cf0d63',
                'label' => __('Label Field 9 radio', 'formularia'),
                'name' => 'label_new_radio_1_9',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_radio',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab485f0d64',
                'label' => __('Label Field 10 radio', 'formularia'),
                'name' => 'label_new_radio_1_10',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_radio',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab4bf18cf1',
                'label' => __('Label new Checkbox', 'formularia'),
                'name' => 'label_new_checkbox_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_checkbox',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab4d818cf2',
                'label' => __('Label Field 1 checkbox', 'formularia'),
                'name' => 'label_new_checkbox_1_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_checkbox',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab4f218cf3',
                'label' => __('Label Field 2 checkbox', 'formularia'),
                'name' => 'label_new_checkbox_1_2',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_checkbox',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab4fd18cf4',
                'label' => __('Label Field 3 checkbox', 'formularia'),
                'name' => 'label_new_checkbox_1_3',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_checkbox',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab50718cf5',
                'label' => __('Label Field 4 checkbox', 'formularia'),
                'name' => 'label_new_checkbox_1_4',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_checkbox',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab53618cf6',
                'label' => __('Label Field 5 checkbox', 'formularia'),
                'name' => 'label_new_checkbox_1_5',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_checkbox',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab54218cf7',
                'label' => __('Label Field 6 checkbox', 'formularia'),
                'name' => 'label_new_checkbox_1_6',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_checkbox',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab54e18cf8',
                'label' => __('Label Field 7 checkbox', 'formularia'),
                'name' => 'label_new_checkbox_1_7',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_checkbox',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab55818cf9',
                'label' => __('Label Field 8 checkbox', 'formularia'),
                'name' => 'label_new_checkbox_1_8',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_checkbox',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab56418cfa',
                'label' => __('Label Field 9 checkbox', 'formularia'),
                'name' => 'label_new_checkbox_1_9',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_checkbox',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab56e18cfb',
                'label' => __('Label Field 10 checkbox', 'formularia'),
                'name' => 'label_new_checkbox_1_10',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_checkbox',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab63b23fdb',
                'label' => __('Label new Color Selector', 'formularia'),
                'name' => 'label_new_color_selector_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_color_selector',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab6aa0518f',
                'label' => __('Label new Numbers', 'formularia'),
                'name' => 'label_new_input_number_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_numerique',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab6c474544',
                'label' => __('Label new Buton', 'formularia'),
                'name' => 'label_new_button_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_button',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab6de87226',
                'label' => __('Label new File', 'formularia'),
                'name' => 'label_new_file_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_file',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab6fb0bf3a',
                'label' => __('Label new Password', 'formularia'),
                'name' => 'label_new_password_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_password',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_561ab72175e96',
                'label' => __('Label New Date', 'formularia'),
                'name' => 'label_new_date_1',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_561aaf2ab6b78',
                            'operator' => '==',
                            'value' => 'new_date',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
//            array (
//                'key' => 'field_5616c5eb3b719',
//                'label' => __('STYLE OF FIELDS', 'formularia'),
//                'name' => '',
//                'type' => 'tab',
//
//            ),//<img src="http://merle-marty.etudiant-eemi.com/perso/A2/wordpress/field_base.png"/>
//            array (
//                'key' => 'field_561e4cad02ba4',
//                'label' => __('Type of Field', 'formularia'),
//                'name' => 'type_of_field',
//                'type' => 'radio',
//                'choices' => array (
//                    'inherit' => '<img src="../wp-content/plugins/formularia/images/champ_base.png"/>',
//                    '5px' => '<img src="../wp-content/plugins/formularia/images/champ_arrondi.png"/>',
//                    '30px' => '<img src="../wp-content/plugins/formularia/images/champ_rond.png"/>',
//                ),
//                'other_choice' => 0,
//                'save_other_choice' => 0,
//                'default_value' => '',
//                'layout' => 'vertical',
//            ),
//            array (
//                'key' => 'field_561e5300295cd',
//                'label' => __('Type of Borders', 'formularia'),
//                'name' => 'new_type_border_style',
//                'type' => 'radio',
//                'choices' => array (
//                    'solid 1px black' => '<img src="../wp-content/plugins/formularia/images/trait-droit.png"/>',
//                    'dashed 1px black' => '<img src="../wp-content/plugins/formularia/images/trait-pointille.png"/>',
//                ),
//                'other_choice' => 0,
//                'save_other_choice' => 0,
//                'default_value' => '',
//                'layout' => 'vertical',
//            ),
//            array (
//                'key' => 'field_561e50e4c0a58',
//                'label' => __('Background Color Field', 'formularia'),
//                'name' => 'new_backgroundcolor_style',
//                'type' => 'color_picker',
//                'default_value' => '',
//            ),
//            array (
//                'key' => 'field_561e556c58d93',
//                'label' => __('Shadow', 'formularia'),
//                'name' => 'new_shadow_style',
//                'type' => 'checkbox',
//                'choices' => array (
//                    'traits droits' => '<img src="../wp-content/plugins/formularia/images/ombre.png"/>',
//                ),
//                'default_value' => '',
//                'layout' => 'vertical',
//            ),
//            array (
//                'key' => 'field_561e50e4c0a56',
//                'label' => __('Background Submit', 'formularia'),
//                'name' => 'new_backgroundcolor_submit_style',
//                'type' => 'color_picker',
//                'default_value' => '',
//            ),
//
//            array (
//                'key' => 'field_561e50e4c0a55',
//                'label' => __('Couleur du text dans les Fields', 'formularia'),
//                'name' => 'new_color_text_style',
//                'type' => 'color_picker',
//                'default_value' => '',
//            ),
//            array (
//                'key' => 'field_563244c30d27d',
//                'label' => __('FORM ACTION', 'formularia'),
//                'name' => '',
//                'type' => 'tab',
//            ),
//            array (
//                'key' => 'field_5616b5766cOP2',
//                'label' => __('File\'s name of "action" of the form', 'formularia'),
//                'name' => 'form_action',
//                'type' => 'text',
//                'default_value' => '',
//                'layout' => 'vertical',
//            )
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'formularia',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
}